### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by DrArmaggedon** [leefsmp/Re-Flex#102]
Hello there, As far as I have checked, the component does not work properly in RTL environment. Any suggestion?

**Comment by leefsmp** [comment]
I don't have any suggestion as I've never worked on RTL env so far. What are the issues you are seeing? Can you provide a codepen demo or similar so I can take a quick look? Thanks

**Comment by leefsmp** [comment]
Closing that ticket for now, feel free to reopen when you can provide a reproducible sample or more details about the issue. Thanks.

**Comment by florinaieremciuc** [comment]
Hi @leefsmp, the issue I've encountered with rtl is related to the way the splitter is being dragged. Here's a demo: https://codesandbox.io/s/pedantic-mahavira-jzdhw?file=/src/App.js
