### ISSUE TITLE
Causes a glitch with Bootstrap

### ISSUE THREAD

**Issue by RickeyWard** [leefsmp/Re-Flex#104]
When dragging a resize bar, it adds body "col-resize" class to change the cursor.  Bootstrap has a class "col-*" that adds margin to the top and bottom of the screen. The overlap of the two cause frustrating visual glitches.

Might be a good idea to scope the global classes using BEM, or possibly just add "ReFlex-" to the classes added to body. "ReFlex-col-resize" and "ReFlex-row-resize"

**Comment by leefsmp** [comment]
Fixed in v 3.0.23, thanks
