### ISSUE TITLE
Bad rerendering.

### ISSUE THREAD

**Issue by anubra266** [leefsmp/Re-Flex#118]
When state changes, It repaints the whole DOM.

**Comment by leefsmp** [comment]
Not sure the understand the issue based on your description, could you provide a codepen/sandbox/ ... demo that reproduces the issue? Thanks.

**Comment by leefsmp** [comment]
Sorry gonna have to close that due to inactivity. Feel free to reopen anytime and provide a reproducible case. Thanks
