### ISSUE TITLE
Wrapping the splitter in a function breaks the library

### ISSUE THREAD

**Issue by casimcdaniels** [leefsmp/Re-Flex#129]
I wanted to use styled components to style my splitter and so attempted to use a simple `styled(ReflexSplitter)`, however, this appears to break the behavior. In fact, just wrapping the component in a simple function that returns a splitter breaks the library functionality. This makes it difficult to style and modify visuals as well as limits ability to extend functionality.

Codepen: https://codesandbox.io/s/react-reflex-bug-v80ep

**Comment by leefsmp** [comment]
well yes that's a limitation of the lib, you cannot wrap those components into higher level functions, however I feel it's pretty straightforward to workaround that, in case of the splitter you can just use an inner component inside the splitter and style that one instead, the issue #65 addresses that topic, [here is the sample](https://codepen.io/leefsmp/pen/PORxWV) for your reference.

**Comment by leefsmp** [comment]
I will close that for now since I assume the workaround I proposed is fairly acceptable, feel free to add more comments if not the case. Thanks.
