### ISSUE TITLE
ReflexHandle - disable resize when focusing other elements - Question

### ISSUE THREAD

**Issue by aniov** [leefsmp/Re-Flex#130]
Hy,

Having the sand-box bellow, how can I stop the reflex interaction when I'm focusing another element ?
(in this case an input element)

https://codesandbox.io/s/agitated-gates-g9u46?file=/src/App.js
![resize-handle-input](https://user-images.githubusercontent.com/21243081/121932310-6a07bd00-cd4d-11eb-9dd4-872a6ef48791.gif)

Thank you in advance.

**Comment by leefsmp** [comment]
One simple way would be to absorb the `mouseDown` event which is used by the handle to start the interaction:

```
<input type="text"value="some text" onMouseDown={handleMouseDown}/>

const handleMouseDown = (e) => {
  e.stopPropagation();
  e.persist();
};
```

**Comment by aniov** [comment]
Thank you, that will do the trick.
