### ISSUE TITLE
Is there any way to prevent sub-containers from automatically recalculating their size?

### ISSUE THREAD

**Issue by nanwy** [leefsmp/Re-Flex#143]
![QQ图片20210806182846](https://user-images.githubusercontent.com/62697454/128497283-b3087f86-ed7b-4067-bd58-946312dd16f5.png)
Let me explain,The largest containers are 1.1, 1.2 sub-containers, 1.1 has 2.1 and 2.2 sub-containers, and 2.1 has 3.1 and 3.2 sub-containers.
![image](https://user-images.githubusercontent.com/62697454/128497569-a91c0606-2d58-4e47-ba08-b778734cbef9.png)

When I drag the lines 1.1 and 1.2, the sizes of 2.1 and 2.2 are recalculated, and I know that's a feature of flex, but I'd like to ask if there's any way to stop sub-containers from calculating size.

Thanks.

**Comment by leefsmp** [comment]
I'm not sure to understand what you are asking... you could set explicit `maxSize` and `minSize` on the `ReflexElements` to constrain their size. If you set `minSize` = `maxSize` = X it should work.

**Comment by nanwy** [comment]
> I'm not sure to understand what you are asking... you could set explicit `maxSize` and `minSize` on the `ReflexElements` to constrain their size. If you set `minSize` = `maxSize` = X it should work.

当我拖动1.1和1.2的splitter时,1.1的大小会改变,同时它的子元素大小也会改变,我想要1.1的子元素大小不能改变,还保持着原来的大小,这个能做到吗?

**Comment by nanwy** [comment]
> I'm not sure to understand what you are asking... you could set explicit `maxSize` and `minSize` on the `ReflexElements` to constrain their size. If you set `minSize` = `maxSize` = X it should work.
When I drag 1.1 and 1.2 of the spotter, 1.1 size will change, and its child size will also change, I want 1.1 child element size can not change, but also maintain the original size, this can do?

**Comment by nanwy** [comment]
> I'm not sure to understand what you are asking... you could set explicit `maxSize` and `minSize` on the `ReflexElements` to constrain their size. If you set `minSize` = `maxSize` = X it should work.

When I drag 1.1 and 1.2 of the spotter, 1.1 size will change, and its child size will also change, I want 1.1 child element size can not change, but also maintain the original size, this can do?

**Comment by leefsmp** [comment]
can you point out which element you want to keep size constant? I'm having a hard time figuring out what you would like to do exactly. Did you check [that demo](https://leefsmp.github.io/Re-Flex/index.html#demo6). If you click the `=` sign in the middle element for example its size is locked when using both splitters above and below.

<img width="619" alt="Screenshot 2021-08-06 at 14 29 04" src="https://user-images.githubusercontent.com/4352502/128510615-edf99967-fe89-4d7b-bd30-7c1dba6276ec.png">
