### ISSUE TITLE
ReflexSplitter is stuck for orientation=horizontal and missing for orientation=vertical

### ISSUE THREAD

**Issue by cegredev** [leefsmp/Re-Flex#144]
I tried running the example shown in the readme but the `ReflexSplitter` either does not move (for `orientation="horizontal"`) or does not appear at all (for `orientation="vertical"`).

I just setup a fresh project using `create-react-app` on Windows 10 and Chrome 92, ran `npm install react-reflex` and adjusted the code to be identical to the example (unless it depends on some quirks like naming or which file the code's in). I'm sure this is my fault but don't know how to fix it.

![horizontal](https://user-images.githubusercontent.com/57912512/128850166-f4b7b746-54cb-4864-b146-6e64094d0908.gif)

![vertical](https://user-images.githubusercontent.com/57912512/128849627-ec7a4a71-655f-43e7-9cad-0f5956f1fff7.png)

**Comment by leefsmp** [comment]
Can't tell anything based on gifs... take a look at the many [codepen examples](https://codepen.io/leefsmp/pens/) in the previous issues, maybe you forgot to import css.

**Comment by cegredev** [comment]
Well, this is the code:

```jsx
import ReactDOM from "react-dom";
import React from "react";

import { ReflexContainer, ReflexSplitter, ReflexElement } from "react-reflex";

import "react-reflex/styles.css";

class ReflexDemo extends React.Component {
	render() {
		return (
			<ReflexContainer orientation="vertical">
				<ReflexElement className="left-pane">
					<div className="pane-content">Left Pane (resizeable)</div>
				</ReflexElement>

				<ReflexSplitter />

				<ReflexElement className="right-pane">
					<div className="pane-content">Right Pane (resizeable)</div>
				</ReflexElement>
			</ReflexContainer>
		);
	}
}

ReactDOM.render(<ReflexDemo />, document.getElementById("root"));
```

It's the example from the readme, except that I replaced the `"reflex-demo"` with `"root"` because that's what the target div's ID is. That's why I didn't post it earlier.

Steps to reproduce:

1. `npx create-react-app demo`
2. `cd demo`
3. `npm install react-reflex`
4. Replace contents of `index.js` with example from `readme.md`
5. Adjust `document.getElementById(...)` accordingly

**Comment by leefsmp** [comment]
check [this](https://github.com/leefsmp/Re-Flex/issues/79) maybe.

**Comment by cegredev** [comment]
That was it, thanks a lot!

Btw, are there any plans to add support for rearranging `ReflexElement`s with drag and drop? If not, I might try to get on that in the future as the project I am working on atm requires it.

**Comment by leefsmp** [comment]
no plans in that direction, that would be quite outside the scope of that library. There are other libs which are focusing on drag and drop such as React dnd, so you would basically need to combine both in a custom component.

**Comment by cegredev** [comment]
Ah okay, gotcha. I'll take a look at dnd and if I find a way to make it work maybe create a fork so others can use it as well. Anyways, thanks for your help!
