### ISSUE TITLE
Remounting of `ReflexElement` children when collapsing panes

### ISSUE THREAD

**Issue by adri1wald** [leefsmp/Re-Flex#148]
Hi, loving react-reflex, but I found a bug which prevents us from using it. Unless we can find a solution :D

I took the example from [react-reflex collapse demo](https://leefsmp.github.io/Re-Flex/index.html#demo9) and tried to adapt it for our app.

However, I noticed that components rendered in non-collapsed `ReflexElement`s were remounting on collapse, causing loss of state.

I made a [minimum reproduction](https://codesandbox.io/s/testing-react-reflex-2o2q5?file=/src/App.js) which shows that the `ReflexElement` child is being remounted on collapse. If you collapse one of the panes, you will see `mounted` logged to the console.

**Comment by leefsmp** [comment]
I think it's a side effect of using `React.cloneElement` internally in the lib, see [this](https://stackoverflow.com/questions/48658382/child-passed-as-prop-gets-re-mounted) maybe. I don't see a workaround here other than using functional components and keeping the state at a higher level in your components hierarchy.
