### ISSUE TITLE
css lost after updating to v2

### ISSUE THREAD

**Issue by barbalex** [leefsmp/Re-Flex#15]
In v1.1.14 my ReflexContainer gets this css:

    .reflex-layout.reflex-container.vertical {
      flex-direction: row;
    }

    .reflex-layout.reflex-container {
        justify-content: flex-start;
        align-items: stretch;
        align-content: stretch;
        display: -webkit-box;
        display: -moz-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        position: relative;
        height: 100%;
        width: 100%;
    }

When I update to v2 this (and probably more on child divs) is missing. So all divs are collapsed.

**Comment by jzoric** [comment]
@barbalex v2 requires css to be added explicitly.

```
// You will need to import the styles separately
// You probably want to do this just once during the bootstrapping phase of your application.
import 'react-reflex/styles.css'
```

**Comment by barbalex** [comment]
Thanks for _immediate_ help

And sorry that I missed that in the readme!

**Comment by leefsmp** [comment]
Packaging strategy has changed in v 2.0.0, that's the only breaking change.
