### ISSUE TITLE
Bug: Setting ```flex``` to 0 results in ```flex``` 1

### ISSUE THREAD

**Issue by StefanRetief** [leefsmp/Re-Flex#152]
If you have a reflex container with multiple reflex elements and set one of the element's ```flex``` props to 0, it will result in the element sizing as if the flex element was set to undefined.

For example:

```javascript
<ReflexContainer>
    <ReflexElement flex={0}>
        <div>test</div>
    </ReflexElement>
    <ReflexElement>
        <div>test 2</div>
    </ReflexElement>
</ReflexContainer>
```

will result in the same sizing as:

```javascript
<ReflexContainer>
    <ReflexElement>
        <div>test</div>
    </ReflexElement>
    <ReflexElement>
        <div>test 2</div>
    </ReflexElement>
</ReflexContainer>
```

When the expected result would typically be that the element is minimized. A work around is to set the flex prop to 0.0001, which reduces the size to a negligible size.

**Comment by leefsmp** [comment]
yes, it's not really a bug but a limitation as a flex of 0 is not supported by the internal logic of the container (it causes a division by 0). See related talk in #146. The workaround is to not render the `ReflexElement` at all or to use `minSize` to avoid flex becoming 0. Hope that helps.
