### ISSUE TITLE
ReflexElement resize 

### ISSUE THREAD

**Issue by Izobov** [leefsmp/Re-Flex#155]
Hello. I have a simple code  https://codesandbox.io/s/vigorous-leakey-d6ehx?file=/src/App.js.
I'm trying to set size by clicking on icon. And it works fine for the first panel but it doesn't work for the second panel. It always throw me an info error like this 
![image](https://user-images.githubusercontent.com/54995954/153458677-c5295201-6e1d-4007-82e1-fe1ffbca6684.png)
Please help me to fix it, cause i don't any ideas how to deal with it

**Comment by leefsmp** [comment]
I guess it's same issue as #101. Use `direction={[-1]}` on the second element.

**Comment by Izobov** [comment]
Yes. It works!)
Thank you very much for the quick response
