### ISSUE TITLE
Not working with nextjs

### ISSUE THREAD

**Issue by vineelsai26** [leefsmp/Re-Flex#166]
This module is not working properly with nextjs. I think it is not properly loading CSS with nextjs I tried everything in the docs to try to fix it but it didn't work at all here is what I used with nextjs https://codesandbox.io/s/icy-resonance-b683ik?file=/pages/index.js, I am not getting any resize bar at all
![image](https://user-images.githubusercontent.com/52851879/171993109-3aea3d47-72dc-478a-859b-7f3a26d5f910.png)

**Comment by nnieddu** [comment]
Hello, I don't think the problem is nextJs cause i have the exact same issue using React last version and with the same provided example (in my typescript project).
("react": "18.1.0", "react-dom": "18.1.0", "typescript": "4.7.3")

**Comment by leefsmp** [comment]
can't tell you without looking at a codepen or a sandbox, you must obviously be doing something wrong as the lib has been confirmed to work on react 18.

**Comment by vineelsai26** [comment]
I have already attached codesandbox link https://codesandbox.io/s/icy-resonance-b683ik?file=/pages/index.js I ported my code to react and it's working perfectly

**Comment by nnieddu** [comment]
Maybe im doing something wrong but i have the same issue :
[https://codesandbox.io/s/winter-sky-ttgnbe?file=/src/index.tsx:43-49](https://codesandbox.io/s/winter-sky-ttgnbe?file=/src/index.tsx:43-49)

**Comment by leefsmp** [comment]
I don't have time to check more closely for now but it's very likely you have a problem with loading of the css, one way or another.

**Comment by Paki90** [comment]
> Hello, I don't think the problem is nextJs because i have the exact same issue using React last version and with the same provided example (in my typescript project), no ReflexSplitter display / usable.
> 
> I notice that if i use : `ReflexContainer orientation="horizontal"` the horizontal type, the splitter appear and seems to be usable (cursor change on hover the slider) but nothing moove when i try.
> 
> (react: 18.1.0, react-dom: 18.1.0, typescript: 4.7.3 and react-reflex 4.0.9)

I have the same issue, splitter show for orientation horizontal, but not vertical. From console I see that splitter height is 0px so that's reason why is not showing. Have no clue why

**Comment by MaksimAndreevich** [comment]
Check your webpack settings.
On our project, he himself renamed the name of the styles (see the attached screenshot).
Maybe this will help you https://github.com/webpack-contrib/css-loader.  Using this package, you can specify which imports will not be processed


<img width="1438" alt="Снимок экрана 2022-06-17 в 14 54 08" src="https://user-images.githubusercontent.com/94795079/174293336-a1b90842-8708-4784-b446-e551c91f733a.png">

**Comment by nnieddu** [comment]
Thanks i will look a that but the Paki90 solution work for me (set the height to auto).
