### ISSUE TITLE
No minHeight or maxHeight for vertical ReflexElement

### ISSUE THREAD

**Issue by michaelwnelson** [leefsmp/Re-Flex#17]
Similar to `minSize` & `maxSize` (width) attributes for a horizontal `<ReflexElement>`.

**Comment by leefsmp** [comment]
those attributes are valid for horizontal or vertical layouts. An element can be resized only along one direction, so it's orientation is irrelevant.

**Comment by michaelwnelson** [comment]
You're correct, I was placing the attributes on the incorrect element, my apologies.

**Comment by leefsmp** [comment]
no worries, it's always hard to assume the bug is on your side. I'm having the same problem ;)
