### ISSUE TITLE
Remove unnecessary console.logs from  ReflexSplitter.js

### ISSUE THREAD

**Issue by SakisTsalk** [leefsmp/Re-Flex#189]
Everytime I access the component two unnecessary console logs appear on the web client console. `hey` `ho`

![image](https://github.com/leefsmp/Re-Flex/assets/54308664/ff393b18-e53f-4d7d-97cb-abdd736b0e67)

Tried to open a PR with a fix but I don't have access. 

Version: 4.2.4

**Comment by leefsmp** [comment]
fixed in `4.2.5`
