### ISSUE TITLE
Question: How to disable the ReflexSplitter?

### ISSUE THREAD

**Issue by karanmidha** [leefsmp/Re-Flex#190]
I am using some custom buttons that I pass as the children of the `ReflexSplitter` as shown below

```
<ReflexSplitter>
  <SplitterButtons />
</reflexSplitter>
```

I want to have a scenario where the users cannot drag the Divider but they can control the layout via the buttons. How can I achieve this?

I tried to make the `pointer-events` property of the `reflex-splitter` as `none` but that also prevents hover. Any workaround for the same? @leefsmp

**Comment by leefsmp** [comment]
I can't think of a workaround, using a splitter and making it unusable by users defeats the purpose. In such scenario you should not use a splitter at all and control the layout with programming logic. There are examples of that in the [demos](https://leefsmp.github.io/Re-Flex/index.html).

**Comment by leefsmp** [comment]
closing as out of scope
