### ISSUE TITLE
can you add a new feature please

### ISSUE THREAD

**Issue by leinjay** [leefsmp/Re-Flex#192]
can you add a new feature ,which can change the layout by dragging?

**Comment by leefsmp** [comment]
I don’t know… you would to add a detailed description of what you have in mind because I can’t say much based on such a thin question. Thanks

**Comment by clarson0** [comment]
@leinjay Have you considered React Mosaic (https://github.com/nomcopter/react-mosaic)?  it's pretty well done and has resizable / draggable panels
