### ISSUE TITLE
Reflex element with a specific flex is displayed incorrectly, when the container size changed

### ISSUE THREAD

**Issue by nguyenvu9405** [leefsmp/Re-Flex#195]
In our application, we rendered ReflexContainer and ReflexElement inside our container. We have a Reflex element with flex: 0.2.
Our container initially have width: 0, height: 0. When the size are changed to a specific width and height larger than 0, the Reflex element width shown in UI is unexpectedly larger than 0.2 size of the container.

**Comment by leefsmp** [comment]
I would suggest not rendering the Reflex container element if the size is 0,0, then once you have a non-zero size you make the first render. Can you try that and let me know if that helps. Thanks

**Comment by nguyenvu9405** [comment]
Hi @leefsmp , thanks for your reply. I have tried the solution you mentioned. However, this did not work in our application which requires the Reflex container element to be there at first render. 
Currently, I'm working around it by only setting `flex` props when the size is non-zero. But this is just a work-around, I hope that there is a official solution for my use-case.

**Comment by leefsmp** [comment]
I don't think there is another solution to it as far as I know unfortunately. There are some computations that cannot take place if the layout is 0. It strikes me that you would not be able to not render the layout if its size is 0,0. Basically what would you render if the size is 0,0, nothing... so why not skipping the rendering at all. I have to close this issue as it falls outside of the supported features of that lib. Maybe someone can come up with a better suggestion but seems a very edge case to me. I had to deal with 0,0 layouts before and doing the workaround of non-rendering has never been a problem so far.
