### ISSUE TITLE
Manage ReflexElement size in state

### ISSUE THREAD

**Issue by michaelwnelson** [leefsmp/Re-Flex#20]
Would it be possible to expose the current state of the ReflexContainer and/or the ReflexElements?

I'd like to assign my currently hardcoded `flex={0.33}` sizes to the component's state and retrieve them on `componentWillUnmount()` so when the user navigates back I can reload their last layout sizes from redux in my component's constructor.

**Comment by leefsmp** [comment]
This seems rather easy to achieve using events that are fired on the splitter or each element upon resize:

`<ReflexElement onResize={this.onResize} name="left-pane">

// need to bind(this) or autobind ...
onResize (event)  {

    const props = event.component.props

    console.log(props.name + ': flex='  + props.flex)

   // from there you can easily store the flex in your redux state ... 
  }

`

**Comment by leefsmp** [comment]
I've added [demo 8](https://leefsmp.github.io/Re-Flex/index.html#demo8) to illustrates that use case.

**Comment by michaelwnelson** [comment]
Thanks, works well! I tried to retrieve the state but initially had it on the wrong element. Thanks for providing an example here and also on your website! Cheers!
