### ISSUE TITLE
Suppress warning about calling preventDefault into ReflexSplitter.onMouseMove

### ISSUE THREAD

**Issue by marc-rutkowski** [leefsmp/Re-Flex#23]
Hi !
And thank you for this great components!

I have notice the following warning into Chrome dev tools console when resizing the ReflexSplitter component:

> Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
onMouseMove @ ReflexSplitter.js:116

The same warning also occurs @ ReflexSplitter.js:156

Maybe these lines can be simply removed?

**Comment by leefsmp** [comment]
seems kinda irrelevant to me... this only occur on touch screens and is specific to chrome 56 as far as I can see.

**Comment by marc-rutkowski** [comment]
ok!

**Comment by leefsmp** [comment]
This warning should be suppressed in v 2.0.9, see discussion in [that issue](https://github.com/leefsmp/Re-Flex/issues/24).
