### ISSUE TITLE
Warning: ReflexElement: `ref` is not a prop. Trying to access it will result in `undefined` being returned.

### ISSUE THREAD

**Issue by JimVanEeden** [leefsmp/Re-Flex#29]
I really need to use a ref on ReflexElement, but it seems it doesn't work properly.

[this](https://github.com/facebook/react/pull/6268) might have something to do with it.

**Comment by leefsmp** [comment]
At the moment I don't think it will work, a ref is passed internally in the `ReflexContainer` to the cloned children... When you say you _"really need to use a ref"_, can you be a bit more explicit about the kind of feature you want to achieve? To me it seems that passing a ref of a div that is inside the `ReflexElement` and takes 100% of its content should be the same final for the user. Or I am missing something...

**Comment by leefsmp** [comment]
I will close that issue for the time being based on my suggestion above, unless you have a strong use case for using a ref on `ReflexElement` itself, in which case feel free to reopen the issue and append some more detailed description. Thanks.
