### ISSUE TITLE
React Deprecation Warning in v15.5.0

### ISSUE THREAD

**Issue by jmquigley** [leefsmp/Re-Flex#3]
I'm receiving the following warning in the console within the library:

> Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

It's related to changes in React v15.5.0 (https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

Using React 15.5.0 and Electron 1.6.2 on Mac OSX 10.12.4.

**Comment by leefsmp** [comment]
Migrated to v1.1.1 to replace React.PropTypes by PropTypes

**Comment by jmquigley** [comment]
FYI, after upgrading to your new version it gives a new warning:

> Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types

**Comment by leefsmp** [comment]
I don't know how to remove this stupid warning, I read the doc at this link and my code isn't calling the validator directly as mentioned. I'm commenting out the PropTypes in v1.1.2 for the time being until I can figure out how to migrate this, super annoying "feature"...

**Comment by Janpot** [comment]
@leefsmp Did some CSI and it seems this warning comes from `react-measure` package. `react-measure` has recently updated to get rid of this warning but I think your bundle still contains an older version. Can you update your modules and bundle again? `react-measure` should be at `1.4.7`.
