### ISSUE TITLE
Package can't be found directly from 'react-reflex'

### ISSUE THREAD

**Issue by vcardins** [leefsmp/Re-Flex#32]
Package can't be found by importing `import { ReflexContainer } from 'react-reflex'`
![image](https://user-images.githubusercontent.com/2383329/32855383-58e56742-c9f6-11e7-9e86-b6fa908ec71b.png)
For now, I'm setting the absolute path 
`import { ReflexContainer } from '../../../node_modules/react-reflex/dist/commonjs';`

**Comment by leefsmp** [comment]
Try v 2.0.11, hopefully [that PR](https://github.com/leefsmp/Re-Flex/pull/30) fixes it. I don't have the issue on my side, probably because I don't use commonjs.

**Comment by vcardins** [comment]
Thanks for the quick response. It works fine now.

**Comment by leefsmp** [comment]
cool
