### ISSUE TITLE
Can't resize panel

### ISSUE THREAD

**Issue by vcardins** [leefsmp/Re-Flex#33]
I'm not being able to resize panels, Am I doing something wrong? Maybe you can see a clue by the markup
![image](https://user-images.githubusercontent.com/2383329/32907838-5d0bc238-cab6-11e7-992e-6e08c7f2d256.png)

**Comment by jzoric** [comment]
From your screenshot I can see that there are no flex values on `reflex-element` e.g
```
<div class="reflex-element left-pane" style="-webkit-box-flex: 0.510563; flex: 0.510563 1 0%;">
...
</div>
```
Also:
1. Why do you need the second `reflex-splitter`?
2. Don't forget to set the `height` on the parent element e.g 
```
<div class="reflex-layout reflex-container vertical " style="height: 300px;"></div>
```
Can you share your code or at least part of it?

**Comment by vcardins** [comment]
The 2nd splitter was not really needed. I have the height set as `100%` for the parent element/container. I'm planning to make part of it open on github but haven't had the time yet, do you have a bitbucket account? I could promptly share it with you now.

**Comment by leefsmp** [comment]
Putting your react code snippet here and css might be enough for a start ...

**Comment by vcardins** [comment]
![image](https://user-images.githubusercontent.com/2383329/32973428-4154a1f8-cbac-11e7-8e4f-bed994fb4f39.png)
https://gist.github.com/vcardins/b89ecf622ca57c97ec1065e1731ad1cb
Let me know if you need me to share anything else.
Thanks!

**Comment by leefsmp** [comment]
What is that JSX.Element thing you are using? My first guess is that is interfere with the lib, when looking at the html, there is no flex property set on the reflex-elements as @jzoric mentionned initially, so something is not being rendered properly.

**Comment by vcardins** [comment]
That JSX.Element thing is just syntax sugar, typescript. I'll have some time this weekend and try to make it work. I'll post my findings. I'm basically comparing the output html with your demo's and they look similar.
Thank you again!

**Comment by leefsmp** [comment]
Your html definitely looks different, there is no flex property on the elements. The lib works fine with typescript, so it an issue with your own implementation. I will close the ticket for now but feel free to add more comments. You should test with a simpler approach first, strip out the HOC components that are wrapping the elements, as I mentioned no wrapper on `ReflexSplitter`. `ReflexElements` can be wrapped, see [Controlled Element](https://leefsmp.github.io/Re-Flex/index.html#demo6) demo.

**Comment by vcardins** [comment]
That's not a problem, Lee. I'll try to find a workaround without changing much my structure, it shouldn't be that hard. Thank you again for your support.

**Comment by leefsmp** [comment]
There is not much point to wrap a splitter, unless you have a valid use case that cannot be handled by css customization + the exposed events. The internal logic in the container doesn't support wrapped splitters because it is doing a check on the element type.
