### ISSUE TITLE
Library lacks typescript typings

### ISSUE THREAD

**Issue by jmquigley** [leefsmp/Re-Flex#4]
No typescript typings for the library.  This means to import the library one must use:

```
const {ReflexContainer, ReflexSplitter, ReflexElement} = require('react-reflex');
```

Instead of

```
import {
  ReflexContainer,
  ReflexSplitter,
  ReflexElement
} from 'react-reflex';
```

The latter import gives the typescript error:

> ERROR in [at-loader] ./src/js/application.tsx:9:8
>     TS7016: Could not find a declaration file for module 'react-reflex'. 

No typings currently exist for the library.

Using React 15.5.0 and Electron 1.6.2 on Mac OSX 10.12.4, typescript 2.2.2.

**Comment by leefsmp** [comment]
I will consider adding TS support in the future but I'm really not a big fan of it. Feel free to submit pull request if you want to add typings yourself. For the time being using require looks like a simple workaround.
