### ISSUE TITLE
Providing an orientation value different than vertical or horizontal lead to max recursion error

### ISSUE THREAD

**Issue by keul** [leefsmp/Re-Flex#43]
OK, this should not be done, but by mistake I used the wrong var and passed an unknow value to `orientation`. I spent a lot of time trying to figure out the issue.

Maybe this can be prevented with just a prop-type warning?

**Comment by leefsmp** [comment]
Sure, this is quite a reasonable check to add. [This commit](https://github.com/leefsmp/Re-Flex/commit/361a92bb943af12727ebfffee4d19c0840691eb9#diff-db6afd20c625b943873faafd28b97323) fixes that behaviour in v 2.1.2.

Thanks.
