### ISSUE TITLE
Safari 11: size is in pixel and not at 100%

### ISSUE THREAD

**Issue by keul** [leefsmp/Re-Flex#44]
There's a difference between Chrome/Firefox and Safari you can also test on the live demo page: https://leefsmp.github.io/Re-Flex/index.html#demo2 (example 2).

Looking at the generated HTML in the browser inspector I see this:

```html
<div class="reflex-element left-pane" style="-moz-box-flex: 0.48329; flex: 0.48329 1 0%;">
  <div style="height: 100%; width: 100%;">
    <div class="pane-content">...
    </div>
  </div>
</div>
```

On Safari:
```html
<div class="reflex-element left-pane" style="-webkit-box-flex: 0.5545325779036824; flex: 0.5545325875282288 1 0%;">
  <div style="height: 250px; width: 783px;">
    <div class="pane-content">...
    </div>
  </div>
</div>
```

So, on Safari we have an inline style with pixels.

This is leading to issues in my environment: if I continue to drag the splitter the `height` continue to raise. Maybe I need to fix more the vertical height of my element, but I'm wondering why there's this difference.

**Comment by leefsmp** [comment]
This result is expected, there is a check in Reflex to detect the browser type and act differently. This is to work around Safari bug that cannot handle nested layouts. Safari is unable to handle nested div's of height 100% causing trouble with that lib, so I implemented a different behaviour which is inlining style in pixels instead.

I am not seeing any difference with the examples or my own website, running Safari 11.0.1. Can you provide more details about what behaviour you are experiencing?

**Comment by keul** [comment]
You don't see any difference because you fixed the height of the container (your `demo-basic-splitter` id behave a CSS rule that say `height: 250px`) so I think you use this height for the inline style.
I fixed the issue in my layout in a similar way, I was just wondering why of the difference. Thanks for clarify this, I was not aware of the issue.

**Comment by leefsmp** [comment]
So it's rather a Safari bug than one with Reflex and it was not clear from your comments but the behaviour of the demos are the same on any browser (at least as far as I tested it). 

You need to have at some point a containing div that has a fixed size, but this could easily be set to `height: 100vh`.

**Comment by keul** [comment]
I'm sorry to bother you again.

I perfectly understood the height issue, but what about `width`? There's still that Safari bug having something like `<div style="height: 250px; width: 100%;">`?

I'm asking because I have also horizontal scrollbars (for few pixels) but manually hacking the lib with a 100% width works perfectly.
My layout is quite complex, I'm not sure how I can share an example of what I get.

**Comment by leefsmp** [comment]
Can you try to use `resizeWidth=false` on `ReflexElement`: `<ReflexElement resizeWidth={false}>`. This should disable injecting the inline width for that element.

**Comment by keul** [comment]
Is working perfectly! Many thanks!
