### ISSUE TITLE
License

### ISSUE THREAD

**Issue by twifty** [leefsmp/Re-Flex#45]
I really needed something like this to work within the Atom editor which uses [etch](https://github.com/atom/etch). I hope you don't mind, but I have used your flex calculation code from the 'container' and created a `etch` compatible components.

However, there is no license attached to your project. I can provide a link to your project and give you credit, but I'm a bit dubious about publishing copied code. Regard this as a formal request for permission and a suggestion to add a [license file](https://opensource.org/licenses/MIT).

**Comment by leefsmp** [comment]
Absolutely. Reflex @2.2.0 is now MIT licensed.

**Comment by twifty** [comment]
Great. Thanks for that.
