### ISSUE TITLE
Handle hidden elements

### ISSUE THREAD

**Issue by ebertmi** [leefsmp/Re-Flex#48]
I've got a maybe specific use case where I am trying to render sometimes inactive elements that cannot be unmounted due to some connected dom nodes. If I do so I am going to loose state information (handled outside of react).

Therefore, I would like to know how it would be possible to avoid using hidden elements (or with a special flag) in the calculation of the element width. Is this possible at the moment? If not, could maybe give me some pointers how I could achieve this?

Thanks in advance.

**Comment by leefsmp** [comment]
I'm not sure what kind of behavior you are looking for... so your elements would be visible or not? If not visible then I can't think of a way right now, if you want to make them inactive as you mentioned then you could either overlay a div on them so controls cannot be used for example or set the `pointer-event: none` in css.  Either way it doesn't seem a question directly related to the use of that component to me.

**Comment by ebertmi** [comment]
I try to explain it a little bit later - got late yesterday.

Scenario:
I am using the library for viewing multiple tabs with mixed content (e.g. file tabs with monaco editor, terminal output with xterm.js, other specific tabs). Now xterm.js has a little bit stupid behavior which destroys the element and losses the previous state and does not offer a real state management. Therefore, I do not remove the component if it is not viewed and instead I set the status as inactive and render it with the HTML `hidden` attribute.

Now if I include an ReflexElement with an child that is hidden it still takes it up in the calculation for the available space. In case of two tabs and only viewing one it still only takes up 50% of the available space.
My goal would be to ignore elements that are hidden from the calculation.

**Comment by ebertmi** [comment]
Thanks a lot for the pen. This is totally fine for my use case.
