### ISSUE TITLE
Using "flex=" property generates warnings

### ISSUE THREAD

**Issue by jmquigley** [leefsmp/Re-Flex#5]
Using "flex=0.2" as a property on ReflexElement generates the warning:

> Warning: a `div` tag (owner: `e`) was passed a numeric string value for CSS property `FlexElement` (value: `0.2`) which will be treated as a unitless number in a future version of React.

Using React 15.5.0 and Electron 1.6.2 on Mac OSX 10.12.4.

**Comment by leefsmp** [comment]
Just try `flex={0.2}`

**Comment by jmquigley** [comment]
That worked, thank you.
