### ISSUE TITLE
Feature request: Resize element with handle

### ISSUE THREAD

**Issue by KenanYusuf** [leefsmp/Re-Flex#52]
It would be nice if you could resize an element with a 'handle' in addition to a splitter.

For example:
![handle](https://user-images.githubusercontent.com/9557798/40880530-b10cdf94-66aa-11e8-864c-c343f91d61e9.jpg)

In the example above, the handle would resize the element it is within in the same way as the splitter before it.

A suggestion of how it could be written:
```jsx
<ReflexContainer>

  <ReflexElement>
    …
  </ReflexElement>

  <ReflexSplitter />

  <ReflexElement>
    <ReflexHandle>
      <div className="handle" />
    </ReflexHandle>
    …
  </ReflexElement>

</ReflexContainer>
```
I don't believe this is possible currently, but please correct me if I am wrong!

PS, thanks for the great component library

**Comment by leefsmp** [comment]
It should be possible by using a controlled custom component. Let me work out an example for that and I will update the issue.

**Comment by leefsmp** [comment]
Here is a pen that addresses your request, let me know if you find this is enough or have questions about it:
https://codepen.io/leefsmp/pen/yEeJjx

**Comment by KenanYusuf** [comment]
That's exactly what I am looking for, thanks for the detailed demo, very helpful 😀

**Comment by leefsmp** [comment]
I found your suggestion interesting and implemented the `ReflexHandle` as you proposed. Take a look at [this demo](https://leefsmp.github.io/Re-Flex/index.html#demo10) and try the handle available in v 2.2.6.

**Comment by KenanYusuf** [comment]
@leefsmp I'm getting an error after updating to 2.2.6

`var childProps = _extends({}, child.props);` is returning null at line 221 in ReflexElement.js

**Comment by leefsmp** [comment]
Can you provide your code? ReflexElement.js is just 203 on my side.

**Comment by KenanYusuf** [comment]
Yup, that's fixed it for me! Thanks again
