### ISSUE TITLE
Can't get a demo to work

### ISSUE THREAD

**Issue by Jefski14** [leefsmp/Re-Flex#53]
Hi, this looks like a great component that would be perfect for what I need, but I can't really get it to work, not even the simplest demo.

Here's my codesandbox: https://codesandbox.io/s/1qjo7q8mll

**Comment by leefsmp** [comment]
It's a css issue, add for example: 
`
.App {
    height: 100px;
}
`

At least one parent of the `ReflexContainer` must have a `height`property. It could be for example `Body with height: 100vh` and then you have `App with height: 100%` if you have to use relative values.

I should add that in the doc/demos at some point. Hope that helps.

**Comment by Jefski14** [comment]
Thanks for the quick response, it works now :+1:
