### ISSUE TITLE
Text inside adjacent panels is being highlighted during drag resize in Firefox 60/61

### ISSUE THREAD

**Issue by stemcc** [leefsmp/Re-Flex#54]
I've noticed this behavior appearing on FF 60 (Ubuntu 18.04) and FF 61 on (Mac OS Sierra). 

Using Chromium on either system (latest stable) this behavior isn't visible.

**Comment by leefsmp** [comment]
Another FF bug ... I don't see how this could be fixed from that lib. You could set `user-select: none` if you want to prevent that from happening. If you want the text to be selectable when user is not resizing, use the splitter events to control the css of those text fields.

Hope that helps.

**Comment by stemcc** [comment]
FYI I'm now also seeing this behavior in Chrome (MacOS 69.0.3497.100) using the latest version on NPM (2.2.9)

**Comment by leefsmp** [comment]
Did you try setting `user-select: none` on those texts as suggested previously?
