### ISSUE TITLE
Disrupt the order of rendering

### ISSUE THREAD

**Issue by bluexiaowei** [leefsmp/Re-Flex#56]
```JavaScript 
import React from 'react';
import { ReflexContainer, ReflexElement, ReflexSplitter } from 'react-reflex';

class View extends React.Component {
  componentDidMount() {
    console.log('View componentDidMount');
  }
  render() {
    return <div>{this.props.children}</div>;
  }
}

class Button extends React.Component {
  componentDidMount() {
    console.log('Button componentDidMount');
  }
  render() {
    return <div>{this.props.children}</div>;
  }
}

export default class Examining extends React.Component {
  componentDidMount() {
    console.log('examining componentDidMount');
  }
  render() {
    return (
      <div>
        <ReflexContainer orientation="vertical">
          <ReflexElement>
            <View>
              <Btn />
            </View>
          </ReflexElement>
          <ReflexSplitter />
        </ReflexContainer>
      </div>
    );
  }
}
```

Result
```JavaScript 
// examining componentDidMount
// Button componentDidMount
// View componentDidMount
```
expectation
```JavaScript 
// Button componentDidMount
// View componentDidMount
// examining componentDidMount
```

**Comment by leefsmp** [comment]
This might be due to the lib internally using [react-measure](https://github.com/souporserious/react-measure) which is playing some tricks on the rendering order. 

Can you elaborate on why this is an issue in your app? So far I haven't seen that behaviour relevant in my apps ...

**Comment by leefsmp** [comment]
Did you mean `console.log(this.Btn);` returns `undefined` (L#26). I think a simple workaround would be to wrap your Button in a custom React component and place the code in `componentDidMount` of that component where you should be able to access the DOM button using a ref.

Let me know if that would work.

**Comment by leefsmp** [comment]
I'll close that for the time being as I don't see it as an issue considering the workaround I gave above. Feel free to reopen and comment if it's not the case. Thanks.
