### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by saulcosta** [leefsmp/Re-Flex#61]
I am researching an issue where `computeFlexDataRec` results in an infinite loop. Unfortunately I haven't been able to reproduce it, but here's the output from my error tracker:

```
RangeError Uncaught RangeError: Maximum call stack size exceeded 
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:717 computeFreeElements
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:745 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
    webpack:///~/react-reflex/dist/es/ReflexContainer.js:769 computeFlexDataRec
```

Based on that it looks like `hasContrain` never gets a truthy value which results in `computeFlexDataRec` being called infinitely.

It appears to only occur on Windows in Chrome (also according to the error tracker).

Any ideas as to what might be causing this?

**Comment by saulcosta** [comment]
It looks like this is triggered on a narrow page when both the `flex` and `minWidth` options are specified. 

I addressed (for now) in our application by setting a page minimum width greater than the sum of the minimum widths of the pane elements, but I'll leave this ticket open for now in case there's a better fix that could be implemented.

**Comment by leefsmp** [comment]
It would help to have a concrete reproducible example for that issue. I agree that the infinite recursion on `computeFlexDataRec` is dangerous, so I'm adding a new prop on `ReflexContainer` in v 2.2.9 named `maxRecDepth` which is defaulted to 100 and will limit the depth of recursion in case it is reached. Ultimately it would be the responsibility of the developer to impose initial constraints on a layout elements which are attainable based on the available width of the page.

    const computeFlexDataRec = (flexDataIn, depth=0) => {

      let hasContrain = false

      const freeElements = computeFreeElements(flexDataIn)

      const freeFlex = computeFreeFlex(flexDataIn)

      const flexDataOut = flexDataIn.map((entry) => {

        if (this.isSplitterElement(entry)) {
          return entry
        }

        const proposedFlex = !entry.constrained
          ? freeFlex / freeElements
          : entry.flex

        const constrainedFlex =
          Math.min(entry.sizeFlex,
            Math.min(entry.maxFlex,
              Math.max(entry.minFlex,
                proposedFlex)))

        const constrained =
          (constrainedFlex !== proposedFlex)

        hasContrain = hasContrain || constrained

        return Object.assign({}, entry, {
          flex: constrainedFlex,
          constrained
        })
      })

      return (hasContrain && depth < this.props.maxRecDepth)
        ? computeFlexDataRec(flexDataOut, depth+1)
        : flexDataOut
    }

I will close that from now, if you have a repro example or further comments feel free to reopen. Thanks
