### ISSUE TITLE
Can't change style of splitter 

### ISSUE THREAD

**Issue by pvaritta** [leefsmp/Re-Flex#65]
Hi,
  I try to change the style of the splitter by doing it bigger(easy to move) and change the color of it.
Anyone know which property that I can use and also if you have any example.

Thanks

**Comment by leefsmp** [comment]
Take a look at the `reflex-splitter` rules in [reflex-styles.scss](https://github.com/leefsmp/Re-Flex/blob/master/src/lib/reflex-styles.scss) and override as needed. 

The splitter component also support passing custom `className` and `style` from its React properties.

Here are two examples of custom splitters:

[Reflex styled splitter](https://codepen.io/leefsmp/pen/BMNqjp)

[Reflex styled splitter component](https://codepen.io/leefsmp/pen/PORxWV)

Ultimately, don't forget the browser inspector is your friend...

<img width="839" alt="screen shot 2019-01-24 at 08 48 18" src="https://user-images.githubusercontent.com/4352502/51662678-e51d7c80-1fb4-11e9-9b48-82bee25f0742.png">
