### ISSUE TITLE
Chrome 72 rendering change

### ISSUE THREAD

**Issue by thecere** [leefsmp/Re-Flex#67]
Giving the `.reflex-container` a `min-height: 0` resolves https://bugs.chromium.org/p/chromium/issues/detail?id=927066 for me.

**Comment by leefsmp** [comment]
I added following css in v 3.0.9, a height of 0 will produce errors in the container:

    .reflex-container.horizontal {
      flex-direction: column;
      min-height: 1px;
    }

    .reflex-container.vertical {
      flex-direction: row;
      min-width: 1px;
    }
