### ISSUE TITLE
Intended delay?

### ISSUE THREAD

**Issue by theluk** [leefsmp/Re-Flex#68]
In the demos, when start draging, initially there is some kind of delay before the containers move. 
Is this intedend? If so, is it possible to switch that off?

**Comment by leefsmp** [comment]
Slow machine/browser :s Looks pretty much instant on my machine (macbook pro), I also didn't notice particular slowness on tablet/phone. 

If you have suggestions to optimize the code I'm happy to hear...

**Comment by theluk** [comment]
![ezgif-2-dd5a176e2fb3](https://user-images.githubusercontent.com/580946/52220320-d8473580-289e-11e9-86e0-45973a459f25.gif)

here is a small example. when dragging, it's fine, it just seems to be the initial drag movement, that somehow seems hanging. 

But never mind, I could look into the source code to see what may be the reason, i was just thinking it is an intended delay

**Comment by theluk** [comment]
within the performance tab there seems to be quite an delay when using this line of code 

        document.body.style.cursor = 'row-resize'

this forces the browser to recalculate the whole style. 

![screen-perf-1](https://user-images.githubusercontent.com/580946/52221400-67554d00-28a1-11e9-9a06-5c9ad46d1cb6.png)

as you can see the Recalculate Style takes up to 250ms. (in my case)
the source of that is the `document.body.style.cursor` assignment. 

Can the cursor be set using css only? Like

```css
.splitter:hover {
   cursor ...
}
.splitter:active {
   cursor ...
}
```

I don't even know if that would work, but just a suggestion.

**Comment by leefsmp** [comment]
Interesting... it's not really suitable to set the cursor style only on the splitter because when dragging it with the mouse it often happens that the mouse pointer goes over an adjacent element, so the effect is that the cursor style is switching back and forth. I will try a css approach on the body as described [here](https://stackoverflow.com/a/5175782/4916074) or maybe just on the container would be sufficient...

**Comment by leefsmp** [comment]
I changed the cursor logic in v3.0.9 to this:

    switch (this.props.orientation) {

      case 'horizontal':
        document.body.classList.add('row-resize')
        this.previousPos = pos.pageY
        break

      case 'vertical':
      default:
        document.body.classList.add('col-resize')
        this.previousPos = pos.pageX
        break
    }

and added css rules:

    body.col-resize {
      cursor: col-resize;
    }

    body.row-resize {
      cursor: row-resize;
    }

As this seems to be a better practice, but unfortunately I am still seeing a delay in IE11 on Windows. Other browsers on Mac/Windows look fine. I guess this is the price to pay to use a deprecated browser :( 

I will close that issue for now, feel free to comment if you have better solution.
