### ISSUE TITLE
Unable to toggle orientation once mounted

### ISSUE THREAD

**Issue by zackinaustin** [leefsmp/Re-Flex#70]
I have usage case where I toggle the props.orientation on the flight. But I run into the issue, for example, when I switch from horizontal to vertical. The flex is calculated based on height instead width. 

Further investigation, I found in the componentWillReceiveProps(), the this.computeFlexData() is based on the old props

**Comment by leefsmp** [comment]
Try latest version `react-reflex@3.0.10` that behaviour should be fixed.

**Comment by leefsmp** [comment]
Feel free to comment if further issue on that topic, closing for now.
