### ISSUE TITLE
Problem with types definitions

### ISSUE THREAD

**Issue by ozeebee** [leefsmp/Re-Flex#71]
Hi, 
It looks like the Typescript types definitions are not packaged with version 3.0.10.
This is probably a packaging issue because the `index.d.ts` types definition file is present at the root of your repository.

Steps to reproduce:

1. Create a typescript react project: 

`yarn create react-app react-reflex-types-bug --typescript`

2. Add `react-reflex` library:

`yarn add react-reflex`

3. Import types in `App.tsx`:

`import { ReflexContainer, ReflexSplitter, ReflexElement } from 'react-reflex'`

4. Try to start or build

`yarn start`

and you get this error:
```
Type error: Could not find a declaration file for module 'react-reflex'. '/Users/xxx/Projects/Perso/tests/react-reflex-types-bug/node_modules/react-reflex/dist/commonjs/index.js' implicitly has an 'any' type.
```

**Comment by leefsmp** [comment]
Should be fixed in v 3.0.12.`index.d.ts`was not packaged in the `/dist` folder.
