### ISSUE TITLE
Data attributes are removed from Re-Flex components

### ISSUE THREAD

**Issue by EricTran5791** [leefsmp/Re-Flex#76]
Hi there,

We're currently trying to add a data attribute to the Re-Flex components like so:

`<ReflexSplitter data-test-id="reflex-splitter">`

The data attribute is intended to be used by our automated tests. We use the data-test-id pattern to build resilient UI tests. However, at run time the data attribute is removed from the component in the DOM. This is what we see:

`<div class="   reflex-splitter">`

Ideally, we would have expected to see:

`<div class="   reflex-splitter" data-test-id="reflex-splitter">`

Here is an example: https://codesandbox.io/s/priceless-ishizaka-3dwuk 

Would it be possible to allow custom data attributes for Re-Flex components?

Thank you for creating Re-Flex! We tried out many re-sizable layout libraries and found many of them to be lacking in features.

**Comment by leefsmp** [comment]
Hi, I'm not familiar with using custom data attributes, but if React supports it, it's fine for me to add support for it in Re-Flex. I need to take a closer look and will get back to you. Thanks

**Comment by leefsmp** [comment]
added to v 3.0.14: support for custom data-attributes in Reflex components. Thanks
