### ISSUE TITLE
Example code does not work

### ISSUE THREAD

**Issue by ishpamintuan** [leefsmp/Re-Flex#79]
Running the example code does not show the correct output, please assist.

![test](https://user-images.githubusercontent.com/17125456/60379690-4da9d300-9a05-11e9-854a-0fb92724878e.png)

**Comment by leefsmp** [comment]
You need to wrap the outer container in a `div` where you specify explicitly an height see [issue #53](https://github.com/leefsmp/Re-Flex/issues/53).

**Comment by ishpamintuan** [comment]
All good now, thanks. 👍
