### ISSUE TITLE
ReflexContainer breaks lifecycle

### ISSUE THREAD

**Issue by andrew-aladev** [leefsmp/Re-Flex#81]
Hello. I've extracted an example with annoying issue:

```
class Child extends Component {
  componentDidMount () {
    console.log("child did mount")
  }

  render () {
    console.log("render child")
    return (<p />)
  }
}

class Parent extends Component {
  componentDidMount () {
    console.log("parent did mount")
  }

  render () {
    console.log("render parent")
    return (
      <ReflexContainer>
        <Child />
      </ReflexContainer>
    )
  }
}
```

```
render parent
parent did mount
render child
child did mount
```

Than replace `ReflexContainer` with `div`:

```
render parent
render child
child did mount
parent did mount
```

So react somehow did't accept children of reflex container.

**Comment by leefsmp** [comment]
Ok this might be due to the fact the lib is using internally `react-measure`. Can you clarify why this is an issue for you? I never encountered a problem linked to that behaviour.

Thanks.

**Comment by andrew-aladev** [comment]
I was able to fix the issue by monkey patching dist in the following way:

```
this.children = React.Children.map(this.getValidChildren(), (child, index) => {
      return child
      ...
```

So removing all `React.createElement` and `React.cloneElement` calls fixes the issue. Parent is not able to detect it's new children, error is somewhere in children mapping. But I am not sure that error is here in this library, it may be in react itself. I won't be surprised that react is defective by design. I will investigate this issue later.

We were using `React Block UI`. It was possible to add blocking layer somewhere in siblings and it will catch all parent actions, because it's `render` was executed before parent `componentDidMount`.

I made the following decision today: it is not possible to rely on parent + children lifecycle. Your application can't consider that children `componentDidMount` or `componentDidUpdate` will be executed before parent. You have to ignore this broken "feature" for now.

**Comment by leefsmp** [comment]
Ok, thanks for the comments, I will then close that for now, if it becomes an issue again feel free to comment here and I will see what can be done.
