### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed, and is not recommended for use.

### ISSUE THREAD

**Issue by IamFonky** [leefsmp/Re-Flex#82]
Hello!
My browser keeps yelling this warning.

´´´
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReflexElement
´´´ 

Can I help you update this or are you already working on it?

**Comment by leefsmp** [comment]
Yeah, haven't got time to migrate so far... All I did is a [place older](https://github.com/leefsmp/Re-Flex/blob/master/src/lib/ReflexContainer.js#L161). 

Feel free to contribute if you want to implement `getDerivedStateFromProps`. 

Thanks

**Comment by IamFonky** [comment]
Okidoki,
I'll try to do that!

**Comment by IamFonky** [comment]
I forked and did some changes but, I really don't know how to use your Demo :yum: 
How to start a server after running `npm run build-demo-dev` ? (sry for my noobish questions)

**Comment by leefsmp** [comment]
just open `index.html` in the browser, no need a server but you could use any local http server of your choice if you prefer.

**Comment by leefsmp** [comment]
Closing that for now as using `UNSAFE_componentWillReceiveProps` should suppress the warning. Migrating `ReflexContainer` to use `getDerivedStateFromProps` is a lot of internal changes so postponing it until it becomes a real problem. `ReflexElement` has now been migrated in v 3.0.18.
