### ISSUE TITLE
Component size 0 warning when display none

### ISSUE THREAD

**Issue by IamFonky** [leefsmp/Re-Flex#84]
Re-Flex is triggering warnings when a Container get rendered or displayed dynamically.

Here's an example that still works with warnings but in my app it keeps a size of 0 and shows no content.

[https://codesandbox.io/s/competent-black-7007c](https://codesandbox.io/s/competent-black-7007c)

I couldn't reproduce that here because of the complexity of the app (Lazy component loading in the ReflexElement and complexity of components like async api calls).

But still, the warning seem to pop up when a container is in a div witch have display:none style and also when a ReflexContainer is rendered in a big component (but not a small one...).

Could it be related to issue #81 ?

**Comment by IamFonky** [comment]
I found a workaround by returning 1.0 with computePixelFlex in ReflexContainer when 0 size detected.
It's clearly not a clean way to resolve the issue but at least I don't have invisible content with this...

**Comment by leefsmp** [comment]
Instead of setting the css to `display: none`, in React you can just skip to render the entire component, this should be both more efficient and lead to better app design. The lib supports that for `ReflexElement` being not rendered.

   render () {
      return (
        this.props.renderContainer &&
        <ReflexContainer>

          this.props.renderElement1 &&
          <ReflexElement>
            Element1
          </ReflexElement>

          this.props.renderElement2 &&
          <ReflexElement>
            Element2
          </ReflexElement>
          
        </ReflexContainer>
      )
    }

**Comment by IamFonky** [comment]
Yes i thought so too so i made a more simple example and sadly i get the same warnings : 

[https://codesandbox.io/s/infallible-butterfly-kk54m](https://codesandbox.io/s/infallible-butterfly-kk54m).

I find out that it's related with the use of React.Children to map the children of the toolbar component.

**Comment by leefsmp** [comment]
Your sample is different, how could you get a warning from a component that isn't even rendered... The ReflexContainers are being instanced at the moment you pass them to the toolbar component. A better way would be to handle the display logic directly in the parent component (in that case App).

You can see than the [Collapsible Panels](https://leefsmp.github.io/Re-Flex/index.html#demo9) demo is not triggering any warning.

**Comment by leefsmp** [comment]
You didn't include any css from `Reflex` in your sample right? If I had a simple css as follow: 

   .reflex-container {
     height: 30px;
   }

Then the warning will disappear. Because any container will get a default height. When including reflex css, you will get `height: 100%`, so you just have to place the `ReflexContainer` in a parent that has a `height != 0`.
