### ISSUE TITLE
Can't pass name prop to ReflexElement

### ISSUE THREAD

**Issue by KevinDenys** [leefsmp/Re-Flex#85]
`          <ReflexElement
            name="table"
            onResize={onFlexChange}
            flex={getFlexState(amountOfVisibleChildren).table.flex}
            className="left-pane"
          >`

> Property 'name' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ReflexElement> & Readonly<ReflexElementProps> & Readonly<{ children?: ReactNode; }>'

**Comment by leefsmp** [comment]
Never used such approach before... can you be more explicit about the use case pls?

**Comment by KevinDenys** [comment]
Fixed it by passing the name to the function as such:  onStopResize={onFlexChange('table')}

**Comment by leefsmp** [comment]
Cool, I'm glad you could work it out!
