### ISSUE TITLE
Gap between mouse cursor and splitter when we are dragging

### ISSUE THREAD

**Issue by onieva** [leefsmp/Re-Flex#92]
Hi,
i am playing with Re-Flex but i think that i found a little issue. When one panel has a parameter "maxSize" set, if several time dragging the splitter beyond the limit of maxSize, in foreach move, appears a little gap that is growing between mouse cursor and splitter. Is this really a issue?, Could you take a look?. 

Attached a video with a example of gap in your page examples

[Re-F_ex Demo.zip](https://github.com/leefsmp/Re-Flex/files/3847719/Re-F_ex.Demo.zip)
Thanks

**Comment by leefsmp** [comment]
Yeah ok I see what you mean, this is not really a bug if I can say but a side effect of how the splitter logic is implemented. At the moment what is considered as long as user is keeping the mouse down after selecting a splitter is the offset, so if you mouse move far left and then right again the offset of cursor will be applied as if you were dragging after selecting the splitter directly, hope that makes sense.

I never felt that behavior was an issue when using the UI so far but I would need to add some logic to start moving the splitter only when mouse pointer is back at its position.

Let's keep that ticket open till I have time for that fix. Thanks.

**Comment by leefsmp** [comment]
The behaviour should now be fixed in `v 3.0.20`, you can test on the [demo](https://leefsmp.github.io/Re-Flex/index.html) page.

**Comment by onieva** [comment]
yes, now is fixed. I am going to close the issue

Thanks!
