### ISSUE TITLE
Package doesn't appear to have proper css associated

### ISSUE THREAD

**Issue by Mik3Qiao** [leefsmp/Re-Flex#96]
Hi, thanks for the great component you wrote, seems promising. I'm a beginner in react :)

But after I created a react app, and add following code:
```javascript 
import React from 'react'
import ReactDOM from 'react-dom'

import {
  ReflexContainer,
  ReflexSplitter,
  ReflexElement
} from 'react-reflex'

import 'react-reflex/styles.css'

/////////////////////////////////////////////////////////
// Basic vertical re-flex layout with splitter
// Adding a splitter between two ReflexElements
// will allow the user to resize them
//
/////////////////////////////////////////////////////////
class ReflexDemo extends React.Component {

  render () {

    return (
      <ReflexContainer orientation="vertical">

        <ReflexElement className="left-pane">
          <div className="pane-content">
            Left Pane (resizeable)
          </div>
        </ReflexElement>

        <ReflexSplitter/>

        <ReflexElement className="right-pane">
          <div className="pane-content">
            Right Pane (resizeable)
          </div>
        </ReflexElement>

      </ReflexContainer>
    )
  }
}

export default ReflexDemo;
```
to a component called ReflexDemo, and imported in index.js file (created with create-react-app), it's shown like the css didnt work properly, also tried to use the "style.css" on the root folder of this github page.

Could you look into it, see what's going on? I have tried other packages on github, haven't encountered such issue yet.

**Comment by Mik3Qiao** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/48367018/72829957-52ee9980-3c45-11ea-8f7b-0094c1bcd1ab.png)
![Screenshot_21](https://user-images.githubusercontent.com/48367018/72829971-5aae3e00-3c45-11ea-8cfa-3718ed9a9550.png)

Images shown like above

**Comment by leefsmp** [comment]
hmm looks like a css issue, make sure the `ReflexContainer` parent dom element has a `height` defined. [Here](https://codepen.io/leefsmp/pen/vrLKdG) is a basic example.

**Comment by Mik3Qiao** [comment]
Thanks for the quick reply, added `height` to `ReflexContainer` parent dom and the first four example from: [https://leefsmp.github.io/Re-Flex/index.html](url) worked.But the fifth one doesn't show the resizer between ''Right Pane Upper-Left" and "RightPane Upper-Right", possibly something wrong with the css again.

For the 6th one, only three buttons were shown.

Thank you, now the basic demos are working, I'll take a look into the 6th one, and see I'm able to fix it.

**Comment by leefsmp** [comment]
Those demos works fine on my side so you must have some css issues that cause a different behaviour in your sample. Note that you can run the demos on your side, they are provided with the package. Run command `npm run build-demo` or `npm build-demo-dev` for HMR and open `index.html` in your browser.

I will close this issue for now, feel free to append comments if needed.
