### ISSUE TITLE
Can the width of the left remain the same in the left and right structures? When the parent div is increased or decreased.

### ISSUE THREAD

**Issue by glossary95** [leefsmp/Re-Flex#97]
Can the width of the left remain the same in the left and right structures? When the parent div is increased or decreased.

Thank you for help

**Comment by leefsmp** [comment]
Sorry could you be a bit more descriptive about the issue... I actually have no idea about what you are talking about. Thanks

**Comment by leefsmp** [comment]
don't think there is an easy way to keep left/right panes size in px constant when resizing the parent. Few suggestions you could try:

- set the size of each pane similar to [Controlled elements Re-Flex example](https://leefsmp.github.io/Re-Flex/index.html#demo6), you would need to set it at each resize event
- set minSize = maxSize = value, but in that case panes will not be resizable manually by user
