### ISSUE TITLE
BUG: Controlled elements not working properly

### ISSUE THREAD

**Issue by martinboksa** [leefsmp/Re-Flex#98]
Hey, 

I use controlled reflex elements in a project with actions like minimize/maximize. There is an issue when you try to control the last element in the list.

Try buttons in the example. 
https://codesandbox.io/s/naughty-williamson-wz7hw

Is there a workaround to fix it? Or any idea how to clear a bug?

**Comment by martinboksa** [comment]
It's working only at the first element :(

**Comment by leefsmp** [comment]
It's not super clear in the doc and examples and it's also not very intuitive but you need to specify the `direction` prop on the `ReflexElements` which indicate, as per the doc:

> direction: Allows to control in which direction(s) the element will shrink/expand when its size property is modified. See Controlled elements demo for more details. Type: -1, 1 or [-1, 1]. Default value: 1.

So your code will work as below:

  ```
<ReflexContainer orientation="horizontal">
  <ReflexElement minSize={45} direction={1}>This is test!</ReflexElement>
  <ReflexSplitter />
  <ReflexElement minSize={45} size={size} direction={-1}>
    This is awesome test 2!
  </ReflexElement>
  <ReflexElement>TEST</ReflexElement>
  </ReflexContainer>
```

This would need to be refactored more properly so the logic automatically detects if a splitter is following an element, hence generating internally values for direction. For the time being it should get you off the hook, if I may say so ;)

**Comment by martinboksa** [comment]
Awesome!  Thanks
